/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2023-09-04 06:20:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/views/shop/../include/nav.jsp", Long.valueOf(1693295310567L));
    _jspx_dependants.put("jar:file:/D:/springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wave-books/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/springworkspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/wave-books/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/shop/../include/footer.jsp", Long.valueOf(1693374150491L));
    _jspx_dependants.put("/WEB-INF/views/shop/../include/aside.jsp", Long.valueOf(1692866099037L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1689218882561L));
    _jspx_dependants.put("/WEB-INF/views/shop/../include/header.jsp", Long.valueOf(1693381857788L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"/resources/jquery/jquery-3.3.1.min.js\"></script>\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<title>Wave_Books</title>\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("	<link href=\"/resources/css/shopView.css\" rel=\"stylesheet\" />\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("	div#asideandcontent { display: flex; }\n");
      out.write("</style>		\n");
      out.write("\n");
      out.write("	\n");
      out.write("<script>\n");
      out.write("	function replyList() {\n");
      out.write("					    	\n");
      out.write("		var gdsNum = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("		$.getJSON(\"/shop/view/replyList\" + \"?n=\" + gdsNum, function(data){\n");
      out.write("			var str = \"\";\n");
      out.write("							    \n");
      out.write("			$(data).each(function(){\n");
      out.write("							     \n");
      out.write("				console.log(data);\n");
      out.write("				\n");
      out.write("				// 날짜 데이터를 보기 쉽게 변환\n");
      out.write("				var repDate = new Date(this.repDate);\n");
      out.write("				repDate = repDate.toLocaleDateString(\"ko-US\")\n");
      out.write("								   \n");
      out.write("				// html 코드 조립\n");
      out.write("				str += \"<li data-repNum='\" + this.repNum + \"'>\"\n");
      out.write("					+ \"<div class='userInfo'>\"\n");
      out.write("					+ \"<span class='userName'>\" + this.userName + \"</span>\"\n");
      out.write("					+ \"<span class='date'>\" + repDate + \"</span>\"\n");
      out.write("					+ \"</div>\"\n");
      out.write("					+ \"<div class='replyContent'>\" + this.repCon + \"</div>\"\n");
      out.write("					\n");
      out.write("					+ \"");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\"\n");
      out.write("					\n");
      out.write("					+ \"</li>\";             \n");
      out.write("			});\n");
      out.write("							    \n");
      out.write("			$(\"section.replyList ol\").html(str);\n");
      out.write("		});\n");
      out.write("	}  \n");
      out.write("</script>	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div id=\"root\">\n");
      out.write("	<header id=\"header\">\n");
      out.write("		<div id=\"header_box\">\n");
      out.write("			");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("    <meta name=\"description\" content=\"\" />\r\n");
      out.write("    <meta name=\"author\" content=\"\" />\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/jquery/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("     <!-- Favicon-->\r\n");
      out.write("     <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/favicon.ico\" />     \r\n");
      out.write("\r\n");
      out.write("	<!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("	<link href=\"/resources/css/styles.css\" rel=\"stylesheet\" />     \r\n");
      out.write("\r\n");
      out.write("	<link href=\"/resources/bootstrap/sb-admin-2.css\" rel=\"stylesheet\" /> \r\n");
      out.write("    <link href=\"/resources/bootstrap/sb-admin-2.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("    \r\n");
      out.write("    <link href=\"/resources/startbootstrap-sb-admin-2-gh-pages/vendor/datatables/dataTables.bootstrap4.min.css\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Header - set the background image for the header in the line below-->\r\n");
      out.write("	<header class=\"py-5 bg-image-full\" style=\"background-image: url('/resources/images/img4.jpg'); width:2000px, 1000px;\" >\r\n");
      out.write("		<div class=\"text-center my-5\">\r\n");
      out.write("            <img class=\"img-fluid rounded-circle mb-4\" src=\"/resources/images/logo4.JPG\" style=\"width:270px;\" alt=\"...\" />\r\n");
      out.write("            <h1 class=\"text-white fs-3 fw-bolder title\"><a href=\"/\">Wave-Books</a></h1>\r\n");
      out.write("            <p class=\"text-white-50 mb-0\">Landing Page Template</p>\r\n");
      out.write("            \r\n");
      out.write("				<!-- 검색창 -->  				\r\n");
      out.write("				          \r\n");
      out.write("            	<div id=\"search_box\" class=\"container-fluid\">\r\n");
      out.write("					<form name=\"search-form\" autocomplete=\"off\" \r\n");
      out.write("					class=\"d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search\">\r\n");
      out.write("						\r\n");
      out.write("						<div class=\"input-group\">\r\n");
      out.write("							<select name=type class=\" form-control bg-light border-0 small\" style=\"width: 60px!important;\">\r\n");
      out.write("								<option selected value=\"gdsName\">제목</option>\r\n");
      out.write("							</select>\r\n");
      out.write("							\r\n");
      out.write("							<input type=\"text\" name=\"keyword\" value=\"\" \r\n");
      out.write("							class=\"form-control bg-light border-0 small\" placeholder=\"Search for...\"\r\n");
      out.write("					              aria-label=\"Search\" aria-describedby=\"basic-addon2\" style=\"width: 190px!important;\"/>\r\n");
      out.write("				         \r\n");
      out.write("				             \r\n");
      out.write("					        <div class=\"input-group-append\">      \r\n");
      out.write("							<input type=\"button\" onClick=\"getSearchList()\" class=\"btn btn-primary\" value=\"검색\" />\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>	\r\n");
      out.write("						\r\n");
      out.write("						<script>\r\n");
      out.write("							function getSearchList(){\r\n");
      out.write("								\r\n");
      out.write("								$('#searchResult').css({\r\n");
      out.write("									\"display\": \"block\"\r\n");
      out.write("								});\r\n");
      out.write("								\r\n");
      out.write("								$.ajax({\r\n");
      out.write("									type: 'GET',\r\n");
      out.write("									url : \"/shop/getSearchList\",\r\n");
      out.write("									data : $(\"form[name=search-form]\").serialize(),\r\n");
      out.write("									success : function(result){\r\n");
      out.write("										console.log(result);\r\n");
      out.write("										//테이블 초기화\r\n");
      out.write("										$('#boardtable > tbody').empty();\r\n");
      out.write("										if(result.length>=1){\r\n");
      out.write("											result.forEach(function(item){\r\n");
      out.write("												str='<tr>'\r\n");
      out.write("												str += \"<td>\" + item.gdsNum + \"</td>\";\r\n");
      out.write("												str+=\"<td>\" + item.gdsName + \"</td>\";\r\n");
      out.write("												str+=\"<td>\" + item.gdsPrice + \"원\" + \"</td>\";\r\n");
      out.write("												str+=\"<td>\" + item.gdsStock + \"개\" + \"</td>\";\r\n");
      out.write("												str+=\"</tr>\"\r\n");
      out.write("												$('#boardtable').append(str);\r\n");
      out.write("							        		})				 \r\n");
      out.write("										}\r\n");
      out.write("									}\r\n");
      out.write("								})\r\n");
      out.write("							}\r\n");
      out.write("						</script>\r\n");
      out.write("						\r\n");
      out.write("					</form>\r\n");
      out.write("					\r\n");
      out.write("					<div id=\"searchResult\" class=\"card shadow mb-4\" style=\"margin: 20px auto; \r\n");
      out.write("							max-width: 600px; display: none;\">\r\n");
      out.write("						<div class=\"card-header py-3\">\r\n");
      out.write("							<h6 class=\"m-0 font-weight-bold text-primary\"> 검색 내역</h6>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<div class=\"table-responsive\">\r\n");
      out.write("					\r\n");
      out.write("								<table id=\"boardtable\" class=\"table table-bordered\" style=\"width:100%; cellspacing: 0;\">\r\n");
      out.write("								\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>	                      \r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("	<!-- Bootstrap core JavaScript -->\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Core plugin JavaScript -->\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom scripts for all pages -->\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level plugins -->\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/vendor/chart.js/Chart.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level custom scripts -->\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/js/demo/chart-area-demo.js\"></script>\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/js/demo/chart-pie-demo.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <!-- Page level plugins -->\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/vendor/datatables/jquery.dataTables.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/vendor/datatables/dataTables.bootstrap4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Page level custom scripts -->\r\n");
      out.write("    <script src=\"/resources/startbootstrap-sb-admin-2-gh-pages/js/demo/datatables-demo.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</header>\n");
      out.write("	\n");
      out.write("	<nav id=\"nav\">\n");
      out.write("		<div id=\"nav_box\">\n");
      out.write("			");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Responsive navbar-->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"/\">Wave_Books</a>\r\n");
      out.write("            <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                    \r\n");
      out.write("                <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                    \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("                \r\n");
      out.write("           </div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</nav>\r\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</nav>\n");
      out.write("	\n");
      out.write("	<div id=\"asideandcontent\">\n");
      out.write("		\n");
      out.write("		<aside id=\"aside\">\n");
      out.write("			");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">   \r\n");
      out.write("    \r\n");
      out.write("    	<div class=\"sidebar-brand-text mx-3\">\r\n");
      out.write("    		<h3 style=\"padding: 20px 0; color: #fff; text-align: center;\">Category</h3>\r\n");
      out.write("    	</div>\r\n");
      out.write("    	\r\n");
      out.write("    	<!-- Divider -->\r\n");
      out.write("        <hr class=\"sidebar-divider\" >\r\n");
      out.write("    	\r\n");
      out.write("    	<li class=\"nav-item\">\r\n");
      out.write("    		<a href=\"/shop/list?c=100&l=1\" class=\"nav-link collapsed\" data-toggle=\"collapse\" \r\n");
      out.write("    		data-target=\"#collapseTwo\" aria-expanded=\"true\" aria-controls=\"collapseTwo\">    		\r\n");
      out.write("    			<span style=\"padding-left: 50px; font-size: 20px;\">국내도서</span>\r\n");
      out.write("    		</a>\r\n");
      out.write("    	\r\n");
      out.write("    		<div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("    			<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("	    			<a class=\"collapse-item\" href=\"/shop/list?c=101&l=2\">소설</a>\r\n");
      out.write("	    			<a class=\"collapse-item\" href=\"/shop/list?c=102&l=2\">시/에세이</a>\r\n");
      out.write("	    			<a class=\"collapse-item\" href=\"/shop/list?c=103&l=2\">인문</a>\r\n");
      out.write("	    		</div>	\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</li>\r\n");
      out.write("    	\r\n");
      out.write("    	<!-- Divider -->\r\n");
      out.write("        <hr class=\"sidebar-divider\" >\r\n");
      out.write("    	\r\n");
      out.write("    	<li class=\"nav-item\">\r\n");
      out.write("	    	<a href=\"/shop/list?c=200&l=1\" class=\"nav-link collapsed\" data-toggle=\"collapse\" \r\n");
      out.write("	    	data-target=\"#collapseUtilities\" aria-expanded=\"true\" aria-controls=\"collapseUtilities\">\r\n");
      out.write("	    		<span style=\"padding-left: 50px; font-size: 20px;\">해외도서</span>\r\n");
      out.write("	    	</a>\r\n");
      out.write("    		\r\n");
      out.write("    		\r\n");
      out.write("    		<div id=\"collapseUtilities\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionSidebar\">\r\n");
      out.write("    			<div class=\"bg-white py-2 collapse-inner rounded\">\r\n");
      out.write("	    			<a class=\"collapse-item\" href=\"/shop/list?c=201&l=2\">문학</a>\r\n");
      out.write("	    			<a class=\"collapse-item\" href=\"/shop/list?c=202&l=2\">예술/건축</a>\r\n");
      out.write("	    			<a class=\"collapse-item\" href=\"/shop/list?c=203&l=2\">인문/사회</a>\r\n");
      out.write("	    		</div>	\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</li>\r\n");
      out.write("    		\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\n");
      out.write("		</aside>\n");
      out.write("		\n");
      out.write("		<div id=\"container_box\">	\n");
      out.write("			<section id=\"content\">\n");
      out.write("				<form role=\"form\" method=\"post\">\n");
      out.write("				   <input type=\"hidden\" name=\"gdsNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("				</form>\n");
      out.write("				\n");
      out.write("				<div class=\"goods\">\n");
      out.write("				   <div class=\"goodsImg\">\n");
      out.write("				    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsImg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("				   </div>\n");
      out.write("				   \n");
      out.write("				   <div class=\"goodsInfo\">\n");
      out.write("				    <p class=\"gdsName\"><span>상품명 </span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("				    \n");
      out.write("				    <p class=\"cateName\"><span>카테고리 </span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.cateName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("				    \n");
      out.write("				    <p class=\"gdsPrice\">\n");
      out.write("				     	<span>가격 </span>");
      if (_jspx_meth_fmt_005fformatNumber_005f0(_jspx_page_context))
        return;
      out.write(" 원\n");
      out.write("				    </p>\n");
      out.write("				    \n");
      out.write("				    <p class=\"gdsStock\">\n");
      out.write("				     	<span>재고 </span>");
      if (_jspx_meth_fmt_005fformatNumber_005f1(_jspx_page_context))
        return;
      out.write(" EA\n");
      out.write("				    </p>\n");
      out.write("				    \n");
      out.write("				    ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				    \n");
      out.write("				    ");
      if (_jspx_meth_c_005fif_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				    \n");
      out.write("				   </div>\n");
      out.write("				      \n");
      out.write("				</div>\n");
      out.write("				\n");
      out.write("				<div class=\"gdsDes\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsDes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("				\n");
      out.write("				<div id=\"reply\">\n");
      out.write("				\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f6(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("				   \n");
      out.write("				   	<section class=\"replyList\">\n");
      out.write("					   <ol>\n");
      out.write("					   	\n");
      out.write("					   ");
      out.write("\n");
      out.write("					\n");
      out.write("					    </ol>  \n");
      out.write("					    \n");
      out.write("					    <script>\n");
      out.write("					    	replyList();\n");
      out.write("					    </script>\n");
      out.write("					    \n");
      out.write("					    <script>\n");
      out.write("						    $(document).on(\"click\", \".modify\", function(){\n");
      out.write("								// $(\".replyModal\").attr(\"style\", \"display:block;\");\n");
      out.write("								$(\".replyModal\").fadeIn(200);\n");
      out.write("								\n");
      out.write("								var repNum = $(this).attr(\"data-repNum\");\n");
      out.write("								var repCon = $(this).parent().parent().children(\".replyContent\").text();\n");
      out.write("								\n");
      out.write("								$(\".modal_repCon\").val(repCon);\n");
      out.write("								$(\".modal_modify_btn\").attr(\"data-repNum\", repNum);\n");
      out.write("								\n");
      out.write("						    });\n");
      out.write("					    </script>\n");
      out.write("					    \n");
      out.write("					    <script>\n");
      out.write("						    $(document).on(\"click\", \".delete\", function(){\n");
      out.write("						    	\n");
      out.write("						    	var deleteConfirm = confirm(\"정말로 삭제하시겠습니까?\");\n");
      out.write("						    	\n");
      out.write("						    	if(deleteConfirm) { \n");
      out.write("						    	\n");
      out.write("							    	  var data = {repNum : $(this).attr(\"data-repNum\")};\n");
      out.write("							    	   \n");
      out.write("							    	  $.ajax({\n");
      out.write("							    	   url : \"/shop/view/deleteReply\",\n");
      out.write("							    	   type : \"post\",\n");
      out.write("							    	   data : data,\n");
      out.write("							    	   success : function(result){\n");
      out.write("							    		   if(result == 1) {\n");
      out.write("							    			   replyList();\n");
      out.write("							    		   } else {\n");
      out.write("							    			   alert(\"작성자 본인만 삭제할 수 있습니다.\")\n");
      out.write("							    		   } \n");
      out.write("							    	   },\n");
      out.write("							    	   error : function() {\n");
      out.write("							    		   alert(\"로그인이 필요합니다.\")\n");
      out.write("							    	   }\n");
      out.write("							    	});\n");
      out.write("						    	}  \n");
      out.write("						    });\n");
      out.write("					    </script>\n");
      out.write("					      \n");
      out.write("					</section>\n");
      out.write("				\n");
      out.write("				</div>\n");
      out.write("						\n");
      out.write("			</section>\n");
      out.write("			\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	\n");
      out.write("\n");
      out.write("\n");
      out.write("	\n");
      out.write("	<footer id=\"footer\">\n");
      out.write("		<div id=\"footer_box\">\n");
      out.write("			");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<style>\r\n");
      out.write("	#footer_ul li { list-style: none; padding-right: 50px!important; }\r\n");
      out.write("</style>     \r\n");
      out.write("\r\n");
      out.write("	<!-- Footer-->\r\n");
      out.write("    <footer class=\"py-5 bg-dark\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("        	<p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2023</p>\r\n");
      out.write("	        <ul class=\"m-0 text-center text-white\" id=\"footer_ul\">\r\n");
      out.write("				<li>사이트 소개</li>\r\n");
      out.write("				<li>이용약관</li>\r\n");
      out.write("				<li>Wave-Books</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    \r\n");
      out.write("	<!-- Bootstrap core JS-->\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("\n");
      out.write("</div>	\n");
      out.write("\n");
      out.write("\n");
      out.write("			<div class=\"replyModal col-lg-6\">\n");
      out.write("	\n");
      out.write("			   	<div class=\"modalContent card shadow mb-4\">\n");
      out.write("			    \n");
      out.write("				    <div class=\"card-body\">\n");
      out.write("				     <textarea class=\"modal_repCon card-body\" name=\"modal_repCon\"></textarea>\n");
      out.write("				    </div>\n");
      out.write("				    \n");
      out.write("				    <div class=\"card-header py-3\" style=\"width: 400px; height: 45px; margin-left: 20px;\">\n");
      out.write("				     <button type=\"button\" class=\"modal_modify_btn btn_primary btn\">수정</button>\n");
      out.write("				     <button type=\"button\" class=\"modal_cancel btn_primary btn btn_block\">취소</button>\n");
      out.write("				    </div>\n");
      out.write("			    \n");
      out.write("			   	</div>\n");
      out.write("			\n");
      out.write("			   	<div class=\"modalBackground\"></div>\n");
      out.write("			   \n");
      out.write("			</div>\n");
      out.write("			\n");
      out.write("			<script>\n");
      out.write("				$(\".modal_cancel\").click(function(){\n");
      out.write("				 	// $(\".replyModal\").attr(\"style\", \"display:none;\");\n");
      out.write("					$(\".replyModal\").fadeOut(200);\n");
      out.write("				});\n");
      out.write("			</script>\n");
      out.write("			\n");
      out.write("			<script>\n");
      out.write("				$(\".modal_modify_btn\").click(function(){\n");
      out.write("				   var modifyConfirm = confirm(\"정말로 수정하시겠습니까?\");\n");
      out.write("				   \n");
      out.write("				   if(modifyConfirm) {\n");
      out.write("					    var data = {\n");
      out.write("						       repNum : $(this).attr(\"data-repNum\"),\n");
      out.write("						       repCon : $(\".modal_repCon\").val()\n");
      out.write("					      };  // ReplyVO 형태로 데이터 생성\n");
      out.write("				    \n");
      out.write("				    $.ajax({\n");
      out.write("					     url : \"/shop/view/modifyReply\",\n");
      out.write("					     type : \"post\",\n");
      out.write("					     data : data,\n");
      out.write("					     success : function(result){\n");
      out.write("				      \n");
      out.write("					  	// result의 값에 따라 동작\n");
      out.write("					      if(result == 1) {\n");
      out.write("					       replyList();		// 리스트 새로고침\n");
      out.write("					       $(\".replyModal\").fadeOut(200);\n");
      out.write("					      } else {\n");
      out.write("					       alert(\"작성자 본인만 수정할 수 있습니다.\");		//  본인이 아닌 경우         \n");
      out.write("					      }\n");
      out.write("				     },\n");
      out.write("				     error : function(){\n");
      out.write("				    	 // 로그인하지 않아서 에러가 발생한 경우\n");
      out.write("				      	alert(\"로그인이 필요합니다.\")\n");
      out.write("				     	}\n");
      out.write("				    });\n");
      out.write("				  }\n");
      out.write("				   \n");
      out.write("				});\n");
      out.write("			</script>\n");
      out.write("	\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/shop/view.jsp(44,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\"\n");
          out.write("					\n");
          out.write("					+ \"<div class='replyFooter'>\"\n");
          out.write("					+ \"<button type='button' class='modify' data-repNum='\" + this.repNum + \"'>M</button>\"\n");
          out.write("					+ \"<button type='button' class='delete' data-repNum='\" + this.repNum + \"'>D</button>\"\n");
          out.write("					+ \"</div>\"\n");
          out.write("					\n");
          out.write("					+ \"");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/shop/../include/nav.jsp(15,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"/\">Home</a></li>\r\n");
          out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"../member/signin\">Login</a></li>\r\n");
          out.write("                    <li class=\"nav-item\"><a class=\"nav-link\" href=\"../member/signup\">Sign Up</a></li>\r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/shop/../include/nav.jsp(21,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("	\r\n");
          out.write("		            \r\n");
          out.write("		            	<li class=\"nav-item\"><span class=\"nav-link\" style=\"color: #fff; margin-right: 30px;\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" 님, 환영합니다.</span></li>\r\n");
          out.write("		            \r\n");
          out.write("		            ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		                    \r\n");
          out.write("		                <li class=\"nav-item\"><a class=\"nav-link\" href=\"/shop/cartList\">장바구니</a></li>\r\n");
          out.write("		                <li class=\"nav-item\"><a class=\"nav-link\" href=\"/shop/orderList\">주문 목록</a></li>\r\n");
          out.write("		                    \r\n");
          out.write("		                <li class=\"nav-item\"><a class=\"nav-link\" href=\"/member/signout\">Logout</a></li>\r\n");
          out.write("                    \r\n");
          out.write("                    \r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/shop/../include/nav.jsp(25,14) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.verify == 9}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		                <li class=\"nav-item\"><a class=\"nav-link\" href=\"/admin/index\">Admin 관리자 화면</a></li>\r\n");
          out.write("		            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f0.setParent(null);
      // /WEB-INF/views/shop/view.jsp(101,26) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setPattern("###,###,###");
      // /WEB-INF/views/shop/view.jsp(101,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsPrice}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f0 = _jspx_th_fmt_005fformatNumber_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f0);
      _jspx_th_fmt_005fformatNumber_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatNumber_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatNumber
    org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag _jspx_th_fmt_005fformatNumber_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag) _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatNumberTag.class);
    boolean _jspx_th_fmt_005fformatNumber_005f1_reused = false;
    try {
      _jspx_th_fmt_005fformatNumber_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatNumber_005f1.setParent(null);
      // /WEB-INF/views/shop/view.jsp(105,26) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setPattern("###,###,###");
      // /WEB-INF/views/shop/view.jsp(105,26) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatNumber_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsStock}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatNumber_005f1 = _jspx_th_fmt_005fformatNumber_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatNumber_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatNumber_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatNumber_005f1);
      _jspx_th_fmt_005fformatNumber_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatNumber_005f1, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatNumber_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/shop/view.jsp(108,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsStock != 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				    \n");
          out.write("				    <p class=\"cartStock\">\n");
          out.write("				     	<span>구입 수량 </span> \n");
          out.write("\n");
          out.write("					   <button type=\"button\" class=\"plus\">+</button>\n");
          out.write("					   <input type=\"number\" class=\"numBox\" min=\"1\" max=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsStock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value=\"1\" readonly=\"readonly\"/>\n");
          out.write("					   <button type=\"button\" class=\"minus\">-</button>\n");
          out.write("					   \n");
          out.write("					   <script>\n");
          out.write("					    $(\".plus\").click(function(){\n");
          out.write("						     var num = $(\".numBox\").val();\n");
          out.write("						     var plusNum = Number(num) + 1;\n");
          out.write("						     \n");
          out.write("						     if(plusNum >= ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsStock}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(") {\n");
          out.write("						      	$(\".numBox\").val(num);\n");
          out.write("						     } else {\n");
          out.write("						      	$(\".numBox\").val(plusNum);            \n");
          out.write("						     }\n");
          out.write("					    });\n");
          out.write("					    \n");
          out.write("					    $(\".minus\").click(function(){\n");
          out.write("						     var num = $(\".numBox\").val();\n");
          out.write("						     var minusNum = Number(num) - 1;\n");
          out.write("						     \n");
          out.write("						     if(minusNum <= 0) {\n");
          out.write("						      	$(\".numBox\").val(num);\n");
          out.write("						     } else {\n");
          out.write("						      	$(\".numBox\").val(minusNum);            \n");
          out.write("						     }\n");
          out.write("					    });\n");
          out.write("					   </script>\n");
          out.write("					</p>    \n");
          out.write("				    \n");
          out.write("				    <p class=\"addToCart\">\n");
          out.write("				     <button type=\"button\" class=\"addCart_btn\">카트에 담기</button>\n");
          out.write("				     \n");
          out.write("				     <script>\n");
          out.write("						  $(\".addCart_btn\").click(function(){\n");
          out.write("						   var gdsNum = $(\"#gdsNum\").val();\n");
          out.write("						   var cartStock = $(\".numBox\").val();\n");
          out.write("						   \n");
          out.write("						   console.log(\"gdsNum : \" + gdsNum);\n");
          out.write("						   console.log(\"cartStock : \" + cartStock);\n");
          out.write("						   \n");
          out.write("						   // ReplyVO 형태로 데이터 생성 \n");
          out.write("						   var data = {\n");
          out.write("								     gdsNum : gdsNum,\n");
          out.write("								     cartStock : cartStock\n");
          out.write("								     };\n");
          out.write("						   \n");
          out.write("						   $.ajax({\n");
          out.write("							    url : \"/shop/view/addCart\",\n");
          out.write("							    type : \"post\",\n");
          out.write("							    data : data,\n");
          out.write("							    success : function(result){\n");
          out.write("							    	\n");
          out.write("							    	if(result == 1) {\n");
          out.write("								     	alert(\"카트 담기 성공\");\n");
          out.write("								     	$(\".numBox\").val(\"1\");\n");
          out.write("							   		 } else {\n");
          out.write("							    		alert(\"로그인이 필요한 기능입니다.\");\n");
          out.write("							    		$(\".numBox\").val(\"1\");\n");
          out.write("							    	}\n");
          out.write("							    \n");
          out.write("							    },\n");
          out.write("							    error : function(){\n");
          out.write("							     	alert(\"카트 담기 실패\");\n");
          out.write("						    	}\n");
          out.write("						  	 });\n");
          out.write("						  });\n");
          out.write("						</script>\n");
          out.write("				    </p>\n");
          out.write("				    \n");
          out.write("				    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent(null);
      // /WEB-INF/views/shop/view.jsp(184,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsStock == 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				    	<p>상품 수량이 부족합니다.</p>\n");
          out.write("				    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f6_reused = false;
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent(null);
      // /WEB-INF/views/shop/view.jsp(196,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<p>소감을 남기시려면 <a href=\"/member/signin\">로그인</a>해주세요.</p>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
      _jspx_th_c_005fif_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f7_reused = false;
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent(null);
      // /WEB-INF/views/shop/view.jsp(200,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("				   	<section class=\"replyForm\">\n");
          out.write("				    	<form role=\"form\" method=\"post\" autocomplete=\"off\">\n");
          out.write("				    	\n");
          out.write("				    		<input type=\"hidden\" name=\"gdsNum\" id=\"gdsNum\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${view.gdsNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("				    	\n");
          out.write("				    		<div class=\"input_area\">\n");
          out.write("				    			<textarea name=\"repCon\" id=\"repCon\"></textarea>\n");
          out.write("				    		</div>\n");
          out.write("\n");
          out.write("							<div class=\"input_area\">\n");
          out.write("								<button type=\"button\" id=\"reply_btn\">소감 남기기</button>\n");
          out.write("								\n");
          out.write("								<script>\n");
          out.write("									$(\"#reply_btn\").click(function(){\n");
          out.write("									  \n");
          out.write("									  var formObj = $(\".replyForm form[role='form']\");\n");
          out.write("									  var gdsNum = $(\"#gdsNum\").val();\n");
          out.write("									  var repCon = $(\"#repCon\").val()\n");
          out.write("									  \n");
          out.write("									  var data = {\n");
          out.write("									    gdsNum : gdsNum,\n");
          out.write("									    repCon : repCon\n");
          out.write("									    };\n");
          out.write("									  \n");
          out.write("									  $.ajax({\n");
          out.write("									   url : \"/shop/view/registReply\",\n");
          out.write("									   type : \"post\",\n");
          out.write("									   data : data,\n");
          out.write("									   success : function(){\n");
          out.write("									    replyList();\n");
          out.write("									    $(\"#repCon\").val(\"\");\n");
          out.write("									   }\n");
          out.write("									  });\n");
          out.write("									 });\n");
          out.write("								</script>\n");
          out.write("								\n");
          out.write("							</div>\n");
          out.write("\n");
          out.write("				    	</form>\n");
          out.write("				   	</section>\n");
          out.write("				   	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
      _jspx_th_c_005fif_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f7_reused);
    }
    return false;
  }
}
